name: Adam Ormsby
favicon: null
layout_spectrum: 0.63749
typography_spectrum: 0.57184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbbdba'
    - '#605050'
    - '#cd000f'
    - '#320004'
    - '#877875'
  brandStrength: 0.75
  lightness: 0.8866165822837502
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
