name: Adam Ormsby
favicon: null
layout_spectrum: 0.16428
typography_spectrum: 0.57184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7bc6ef'
    - '#292921'
    - '#f96b00'
    - '#6a6b50'
  brandStrength: 0.1875
  lightness: 0.8866165822837502
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
